version: '2.0'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/opt/etaromangan/public
    depends_on:
      - php
      - asset_builder

  php:
    build:
      context: ./
      dockerfile: app.prod.dockerfile
    restart: always
    volumes:
      - .:/opt/etaromangan
      - /opt/etaromangan/vendor/
      - /opt/etaromangan/node_modules/
      - app_storage:/opt/etaromangan/storage # Uploads and data storage
      - app_cache:/opt/etaromangan/storage # Laravel cache directory
    ports:
      - "8000:9000"
    env_file:
      - .env.prod.docker
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=[mysql_root_password]
      - MYSQL_DATABASE=etaromangan
      - MYSQL_USER=etaromangan
      - MYSQL_PASSWORD=[mysql_password]

  asset_builder:
    build:
      context: ./
      dockerfile: asset_builder.prod.dockerfile
    volumes:
      - ./webpack.mix.js:/opt/etaromangan/webpack.mix.js:ro
      - ./resources/assets:/opt/etaromangan/resources/assets:ro
      - ./public:/opt/etaromangan/public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=mysql
    restart: always
    ports:
     - 1234:80

volumes:
  app_storage:
    driver: local
  app_cache:
    driver: local
  mysql_data:
    driver: local

